My Blog
khanfarhan10/khanfarhan10.github.io pull request #4
Opened 2020-12-23 20:34 UTC by Vamsi995

## Summary

## Context

2020-12-23 20:54 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +excerpt: "This is the inital blog post to derive a generalized interest for the project of Text Sentiment Analysis."
Give a  valuable description in your excerpt.

2020-12-23 20:54 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +tags:
Write your own tags!
It can be your college name or your fields of interests. Like NLP, Python or others.

2020-12-23 20:55 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +title: "WoCabulary - My Woc Blog"
Innovative name there! Great.

2020-12-23 20:56 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +og_image: /assets/images/WoC2020logo.jpg
Change all the images to your own favourite image. Make the website stand out and not dull. :)
All images go under assets/images . https://github.com/khanfarhan10/khanfarhan10.github.io/tree/master/assets/images

2020-12-23 20:57 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +  overlay_image: /assets/images/WoC2020logo.jpg
Same with these imgs.

2020-12-23 20:57 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +  caption: "Image credit: [**Winter of Code**](https://winterofcode.com/) on [**Instagram**](https://www.instagram.com/winterofcode/)"
If you provide a header image copied from somewhere, please acknowledge the source.

2020-12-23 20:58 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +  actions:
You can customize and add your own buttons ! Try it!

2020-12-23 20:58 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +author: Sai Vamsi Alisetti
Just adding the author wont work, you have to change authors.yml in the _data section! 
https://github.com/khanfarhan10/khanfarhan10.github.io/blob/master/_data/authors.yml

Or watch the YT video : https://youtu.be/F5_tRRIyyiY

2020-12-23 20:59 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +
Rest is great! I appreciate the efforts!!! Add some external links if you wish to and make the page more interesting!

2020-12-23 21:00 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +  actions:
It can be a nested list!

2020-12-23 21:01 UTC, khanfarhan10 commented on _woc/WoCabulary.md
> +title: "WoCabulary - My Woc Blog"
If you need help with the blog :
https://github.com/khanfarhan10/khanfarhan10.github.io/pull/2/files
https://github.com/khanfarhan10/khanfarhan10.github.io/pull/3/files
https://github.com/khanfarhan10/khanfarhan10.github.io/pull/1/files

2020-12-23 21:01 UTC, khanfarhan10 requested changes
Make changes as required

2020-12-24 16:26 UTC, Vamsi995 commented
I made the necessary changes.

2020-12-26 17:25 UTC, khanfarhan10 commented
Looks Good to go!

2020-12-26 17:26 UTC, merged